version: '3.1'

services:

    db:
        image: mysql:latest
        container_name: todoapp
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todoapp
            MYSQL_USER: user
            MYSQL_PASSWORD: pwd
        ports:
            - 3306:3306
        volumes:
            - ./db-dump:/docker-entrypoint-initdb.d